services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend:
    restart: "no"
    ports:
      - 8000:8000
    build:
      context: ./backend
    command:
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --reload
      - --port
      - "8000"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.env
            - .env
        - path: ./backend/pyproject.toml
          action: rebuild

